config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  root to: "admin/orders#index"

  namespace :admin do
    resources :orders
    resources :suppliers, except: :show
  end
end

app/models/supplier.rb
# == Schema Information
#
# Table name: suppliers
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Supplier < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  validates :name, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/controllers/admin/suppliers_controller.rb
# frozen_string_literal: true

class Admin::SuppliersController < Admin::BaseController
  before_action :find_supplier, only: %i[edit update destroy]

  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to admin_suppliers_path, notice: "Supplier was successfully created."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      redirect_to admin_suppliers_path, notice: "Supplier was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @supplier.destroy
    redirect_to admin_suppliers_path, alert: "Supplier was successfully destroyed."
  end

  private

  def find_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:name)
  end
end

app/views/admin/suppliers/_form.html.erb
<!-- component -->
<%= form_with(model: [:admin, supplier]) do |f| %>
  <div class="flex items-center justify-center">
    <div class="grid bg-white rounded-lg shadow-xl w-11/12 md:w-9/12 lg:w-1/2">

      <div class="grid grid-cols-1 mt-5 mx-7">
        <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">廠商名稱</label>
        <%= f.text_field :name, class: "py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" %>
      </div>

      <div class='flex items-center justify-center  md:gap-8 gap-4 pt-5 pb-5'>
        <%= link_to "Cancel", admin_suppliers_path, class: "w-auto bg-gray-500 hover:bg-gray-700 rounded-lg shadow-xl font-medium text-white px-4 py-2" %>
        <%= f.button "Save", class: "w-auto bg-purple-500 hover:bg-purple-700 rounded-lg shadow-xl font-medium text-white px-4 py-2" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/suppliers/edit.html.erb
<%= render partial: 'shared/top', locals: { title: '編輯供應商'} %>

<%= render "form", supplier: @supplier %>

app/views/admin/suppliers/index.html.erb
<%= render partial: 'shared/top', locals: { title: '供應商管理'} %>
<%= render partial: 'shared/new_button', locals: { path: new_admin_supplier_path, title: '新增供應商'} %>

<div class="overflow-x-auto">
  <div class="flex items-center justify-center font-sans overflow-hidden">
    <div class="w-full px-6">
      <div class="bg-white shadow-md rounded my-6">
        <table class="min-w-max w-full table-auto">
          <thead>
            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
              <th class="py-3 px-6 text-left">廠商名稱</th>
              <th class="py-3 px-6 text-left">Client</th>
              <th class="py-3 px-6 text-center">Status</th>
              <th class="py-3 px-6 text-center">Actions</th>
            </tr>
          </thead>
          <tbody class="text-gray-600 text-sm font-light">
            <% @suppliers.each do |supplier| %>
              <tr class="border-b border-gray-200 hover:bg-gray-100">
                <td class="py-3 px-6 text-left whitespace-nowrap">
                  <div class="flex items-center">
                    <span class="font-medium"><%= supplier.name %></span>
                  </div>
                </td>
                <td class="py-3 px-6 text-left">
                  <div class="flex items-center">
                    <div class="mr-2">
                      <img class="w-6 h-6 rounded-full" src="https://randomuser.me/api/portraits/men/1.jpg"/>
                    </div>
                    <span>Eshal Rosas</span>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">Active</span>
                </td>
                <td class="py-3 px-6 text-center">
                  <div class="flex item-center justify-center">
                    <!-- <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                    </div> -->
                  <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                    <%= link_to edit_admin_supplier_path(supplier) do %>
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                      </svg>
                    <% end %>
                  </div>
                  <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                    <%= link_to admin_supplier_path(supplier), method: :delete do %>
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                      </svg>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/suppliers/new.html.erb
<%= render partial: 'shared/top', locals: { title: '新增供應商'} %>

<%= render "form", supplier: @supplier %>